<a href="https://colab.research.google.com/github/Windbladejg7/Notebooks/blob/main/Python_Practice_1_18_08_2025.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
#Día 1
import numpy as np
arreglo = np.array([x for x in range(1,6)])

arreglo1 = np.arange(1, 5)
arreglo1

arreglo2 = np.linspace(1, 2, 10) #(inicio, fin, cantidad_de_elementos)
arreglo2

#np.random.randint()}

#Indexing
print(arreglo[:3]) #Exclusivo
print(arreglo[2:]) #Inclusivo
print(arreglo[::-1]) #Imprimer en reversa

#Vectorizacion
print(arreglo+5) #Broadcasting, operar sobre arreglos de diferentes dimensiones

#Ufuncs
np.sum(arreglo) #Aggregation function: Se pueden usar con el arreglo directamente
aleatorios = np.random.randint(10, size=5)
print(aleatorios)
np.max(aleatorios)
aleatorios.mean()
aleatorios.argmin()
booleanos = np.array([False, False, False, False])
booleanos.any() #Retorna verdadero si hay algún verdadero
booleanos.dtype
booleanos.shape
aleatorios > 3 #Ufunc
print(aleatorios[aleatorios == 5]) #Boolean masking
arreglo[[1, 4]] #Fancy indexing: Pasar una lista para indexar

[1 2 3]
[3 4 5]
[5 4 3 2 1]
[ 6  7  8  9 10]
[9 2 4 1 6]
[]


array([2, 5])